version: "3.9"

services:
  backend:
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --no-input &&
      gunicorn core.wsgi --bind 0.0.0.0:8000"
    volumes:
      - ./core:/app
      - static:/app/static
      - media:/app/media
    expose:
      - "8000"
    environment:
      - SECRET_KEY=test
      - DEBUG=False
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
    restart: always

  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    command: sh -c "redis-server --save 60 1 --loglevel warning"
    restart: always

  worker:
    container_name: worker
    image: worker
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "celery -A core worker -l INFO"
    volumes:
      - ./core:/app
    depends_on:
      - backend
      - redis
    restart: always

  worker_beat:
    container_name: worker_beat
    image: worker_beat
    build:
      context: .
      dockerfile: Dockerfile
    command: sh -c "celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler"
    volumes:
      - ./core:/app
    depends_on:
      - backend
      - redis
    restart: always

  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static:/home/app/static
      - media:/home/app/media
    ports:
      - "80:80"
    restart: always


volumes:
  static:
  media:
