# Generated by Django 4.2.10 on 2024-03-06 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='upldated_date',
            new_name='updated_date',
        ),
    ]
