# Generated by Django 4.2.10 on 2024-03-06 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 10, 0, 53, 575506, tzinfo=datetime.timezone.utc)),
        ),
    ]
