# Generated by Django 4.2.10 on 2024-03-06 11:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 11, 33, 19, 980391, tzinfo=datetime.timezone.utc)),
        ),
    ]
