name: Django Project

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup Docker Compose
      run: docker compose -f docker-compose-production.yml up  --build -d
